services:
  analyseprojet:
    build: .
    container_name: analyseprojet-app
    restart: unless-stopped
    mem_limit: 768m
    networks:
      - web
    volumes:
      - ./data:/app/data # persistance SQLite + clés Data Protection
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AllowedHosts=${APP_DOMAIN:?APP_DOMAIN manquant dans .env}
      - AdminAccount__Email=${ADMINACCOUNT__EMAIL:?ADMINACCOUNT__EMAIL manquant dans .env}
      - AdminAccount__Password=${ADMINACCOUNT__PASSWORD:?ADMINACCOUNT__PASSWORD manquant dans .env}

networks:
  web:
    external: true
