services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/app/data # persistance SQLite
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/analyseprojet.db
      - DatabaseProvider=Sqlite
      - ASPNETCORE_ENVIRONMENT=Production
      - AdminAccount__Email=${ADMINACCOUNT__EMAIL}
      - AdminAccount__Password=${ADMINACCOUNT__PASSWORD}

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - app

volumes:
  caddy_data:
