// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Data.Migrations
{
    [DbContext(typeof(AnalyseProjetDbContext))]
    partial class AnalyseProjetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Api.Data.Entities.Acteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonction")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId", "Code")
                        .IsUnique();

                    b.ToTable("Acteurs", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.Automatisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Declencheur")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjetId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ValidationHumaine")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId", "Code")
                        .IsUnique();

                    b.ToTable("Automatisations", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Secteur")
                        .HasColumnType("TEXT");

                    b.Property<string>("Taille")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.CompteurCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DernierNumero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefixe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId", "Prefixe")
                        .IsUnique();

                    b.ToTable("CompteursCode", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.CritereAcceptation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FonctionnaliteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Given")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Then")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("When")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FonctionnaliteId");

                    b.ToTable("CriteresAcceptation", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.DecisionRegistre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternativesEcartees")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Justification")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId", "Code")
                        .IsUnique();

                    b.ToTable("DecisionsRegistre", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.DocumentMetier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .HasColumnType("TEXT");

                    b.Property<string>("DureeConservation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origine")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId", "Code")
                        .IsUnique();

                    b.ToTable("DocumentsMetier", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.Entite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attributs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Relations")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId", "Code")
                        .IsUnique();

                    b.ToTable("Entites", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.EtapeProcessus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Acteur")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("DureeEstimee")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErreursConnues")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExempleDescription")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExempleValide")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outil")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProcessusId");

                    b.ToTable("EtapesProcessus", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.Fonctionnalite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActeurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Priorite")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActeurId");

                    b.HasIndex("ProjetId", "Code")
                        .IsUnique();

                    b.ToTable("Fonctionnalites", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.HistoriqueModification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AncienneValeur")
                        .HasColumnType("TEXT");

                    b.Property<string>("Champ")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntiteType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NouvelleValeur")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntiteType", "EntiteId");

                    b.ToTable("HistoriqueModifications", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.InformationRegistre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntiteReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntiteType")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Valeur")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.HasIndex("EntiteType", "EntiteReferenceId");

                    b.HasIndex("ProjetId", "Code")
                        .IsUnique();

                    b.ToTable("InformationsRegistre", null, t =>
                        {
                            t.HasCheckConstraint("CK_InformationRegistre_LienPolymorpheCoherent", "(\"EntiteType\" IS NULL AND \"EntiteReferenceId\" IS NULL) OR (\"EntiteType\" IS NOT NULL AND \"EntiteReferenceId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Api.Data.Entities.LienTracabilite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CritereAcceptationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EntiteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FonctionnaliteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProblemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CritereAcceptationId");

                    b.HasIndex("EntiteId");

                    b.HasIndex("FonctionnaliteId");

                    b.HasIndex("ProblemeId");

                    b.ToTable("LiensTracabilite", null, t =>
                        {
                            t.HasCheckConstraint("CK_LienTracabilite_AuMoinsUnLien", "\"ProblemeId\" IS NOT NULL OR \"FonctionnaliteId\" IS NOT NULL OR \"EntiteId\" IS NOT NULL OR \"CritereAcceptationId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Api.Data.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActeurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntiteConcernee")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PeutCreer")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PeutModifier")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PeutSupprimer")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PeutValider")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PeutVoir")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActeurId");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateMaj")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId", "Numero")
                        .IsUnique();

                    b.ToTable("Phases", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.Probleme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CoutEstime")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Frequence")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Gravite")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImpactTempsHeuresMois")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProjetId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ScoreCalcule")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId", "Code")
                        .IsUnique();

                    b.ToTable("Problemes", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.Processus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Declencheur")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId", "Code")
                        .IsUnique();

                    b.ToTable("Processus", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.Projet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("NiveauMaturite")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotesPreparation")
                        .HasColumnType("TEXT");

                    b.Property<string>("StackEnvisagee")
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Projets", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.QuestionRegistre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Importance")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.HasIndex("ProjetId", "Code")
                        .IsUnique();

                    b.ToTable("QuestionsRegistre", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.RisqueRegistre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Impact")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mesure")
                        .HasColumnType("TEXT");

                    b.Property<string>("Probabilite")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId", "Code")
                        .IsUnique();

                    b.ToTable("RisquesRegistre", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Api.Data.Entities.Acteur", b =>
                {
                    b.HasOne("Api.Data.Entities.Projet", "Projet")
                        .WithMany("Acteurs")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("Api.Data.Entities.Automatisation", b =>
                {
                    b.HasOne("Api.Data.Entities.Projet", "Projet")
                        .WithMany("Automatisations")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("Api.Data.Entities.CritereAcceptation", b =>
                {
                    b.HasOne("Api.Data.Entities.Fonctionnalite", "Fonctionnalite")
                        .WithMany("CriteresAcceptation")
                        .HasForeignKey("FonctionnaliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fonctionnalite");
                });

            modelBuilder.Entity("Api.Data.Entities.DecisionRegistre", b =>
                {
                    b.HasOne("Api.Data.Entities.Projet", "Projet")
                        .WithMany("Decisions")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("Api.Data.Entities.DocumentMetier", b =>
                {
                    b.HasOne("Api.Data.Entities.Projet", "Projet")
                        .WithMany("Documents")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("Api.Data.Entities.Entite", b =>
                {
                    b.HasOne("Api.Data.Entities.Projet", "Projet")
                        .WithMany("Entites")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("Api.Data.Entities.EtapeProcessus", b =>
                {
                    b.HasOne("Api.Data.Entities.Processus", "Processus")
                        .WithMany("Etapes")
                        .HasForeignKey("ProcessusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Processus");
                });

            modelBuilder.Entity("Api.Data.Entities.Fonctionnalite", b =>
                {
                    b.HasOne("Api.Data.Entities.Acteur", "Acteur")
                        .WithMany("Fonctionnalites")
                        .HasForeignKey("ActeurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Data.Entities.Projet", "Projet")
                        .WithMany("Fonctionnalites")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acteur");

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("Api.Data.Entities.InformationRegistre", b =>
                {
                    b.HasOne("Api.Data.Entities.Phase", "Phase")
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Data.Entities.Projet", "Projet")
                        .WithMany("Informations")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("Api.Data.Entities.LienTracabilite", b =>
                {
                    b.HasOne("Api.Data.Entities.CritereAcceptation", "CritereAcceptation")
                        .WithMany()
                        .HasForeignKey("CritereAcceptationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Api.Data.Entities.Entite", "Entite")
                        .WithMany("LiensTracabilite")
                        .HasForeignKey("EntiteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Api.Data.Entities.Fonctionnalite", "Fonctionnalite")
                        .WithMany("LiensTracabilite")
                        .HasForeignKey("FonctionnaliteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Api.Data.Entities.Probleme", "Probleme")
                        .WithMany("LiensTracabilite")
                        .HasForeignKey("ProblemeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CritereAcceptation");

                    b.Navigation("Entite");

                    b.Navigation("Fonctionnalite");

                    b.Navigation("Probleme");
                });

            modelBuilder.Entity("Api.Data.Entities.Permission", b =>
                {
                    b.HasOne("Api.Data.Entities.Acteur", "Acteur")
                        .WithMany("Permissions")
                        .HasForeignKey("ActeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acteur");
                });

            modelBuilder.Entity("Api.Data.Entities.Phase", b =>
                {
                    b.HasOne("Api.Data.Entities.Projet", "Projet")
                        .WithMany("Phases")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("Api.Data.Entities.Probleme", b =>
                {
                    b.HasOne("Api.Data.Entities.Projet", "Projet")
                        .WithMany("Problemes")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("Api.Data.Entities.Processus", b =>
                {
                    b.HasOne("Api.Data.Entities.Projet", "Projet")
                        .WithMany("Processus")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("Api.Data.Entities.Projet", b =>
                {
                    b.HasOne("Api.Data.Entities.Client", "Client")
                        .WithMany("Projets")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Api.Data.Entities.QuestionRegistre", b =>
                {
                    b.HasOne("Api.Data.Entities.Phase", "Phase")
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Data.Entities.Projet", "Projet")
                        .WithMany("Questions")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("Api.Data.Entities.RisqueRegistre", b =>
                {
                    b.HasOne("Api.Data.Entities.Projet", "Projet")
                        .WithMany("Risques")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Api.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Api.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Api.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Data.Entities.Acteur", b =>
                {
                    b.Navigation("Fonctionnalites");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Api.Data.Entities.Client", b =>
                {
                    b.Navigation("Projets");
                });

            modelBuilder.Entity("Api.Data.Entities.Entite", b =>
                {
                    b.Navigation("LiensTracabilite");
                });

            modelBuilder.Entity("Api.Data.Entities.Fonctionnalite", b =>
                {
                    b.Navigation("CriteresAcceptation");

                    b.Navigation("LiensTracabilite");
                });

            modelBuilder.Entity("Api.Data.Entities.Probleme", b =>
                {
                    b.Navigation("LiensTracabilite");
                });

            modelBuilder.Entity("Api.Data.Entities.Processus", b =>
                {
                    b.Navigation("Etapes");
                });

            modelBuilder.Entity("Api.Data.Entities.Projet", b =>
                {
                    b.Navigation("Acteurs");

                    b.Navigation("Automatisations");

                    b.Navigation("Decisions");

                    b.Navigation("Documents");

                    b.Navigation("Entites");

                    b.Navigation("Fonctionnalites");

                    b.Navigation("Informations");

                    b.Navigation("Phases");

                    b.Navigation("Problemes");

                    b.Navigation("Processus");

                    b.Navigation("Questions");

                    b.Navigation("Risques");
                });
#pragma warning restore 612, 618
        }
    }
}
